version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    networks:
      - app_network
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=your_database
      - DB_USERNAME=your_username
      - DB_PASSWORD=your_password
    ports:
      - "8080:80"  # Expose app on port 8080

  db:
    image: mysql:5.7
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
